# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtStreamlabsUrl = QtWidgets.QLineEdit(self.groupBox)
        self.txtStreamlabsUrl.setObjectName("txtStreamlabsUrl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtStreamlabsUrl)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtClientId = QtWidgets.QLineEdit(self.groupBox)
        self.txtClientId.setObjectName("txtClientId")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtClientId)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtUsername = QtWidgets.QLineEdit(self.groupBox)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtUsername)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblStatus = QtWidgets.QLabel(self.groupBox)
        self.lblStatus.setObjectName("lblStatus")
        self.horizontalLayout.addWidget(self.lblStatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnConnect = QtWidgets.QPushButton(self.groupBox)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout.addWidget(self.btnConnect)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.grpDonation = QtWidgets.QGroupBox(self.centralwidget)
        self.grpDonation.setObjectName("grpDonation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.grpDonation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.grpDonation)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.grpDonation)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.grpDonation)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtLastTitle = QtWidgets.QLineEdit(self.grpDonation)
        self.txtLastTitle.setReadOnly(True)
        self.txtLastTitle.setObjectName("txtLastTitle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLastTitle)
        self.txtLastUrl = QtWidgets.QLineEdit(self.grpDonation)
        self.txtLastUrl.setReadOnly(True)
        self.txtLastUrl.setObjectName("txtLastUrl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtLastUrl)
        self.txtLastTimestamp = QtWidgets.QLineEdit(self.grpDonation)
        self.txtLastTimestamp.setReadOnly(True)
        self.txtLastTimestamp.setObjectName("txtLastTimestamp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtLastTimestamp)
        self.label_7 = QtWidgets.QLabel(self.grpDonation)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtDonationUsername = QtWidgets.QLineEdit(self.grpDonation)
        self.txtDonationUsername.setReadOnly(True)
        self.txtDonationUsername.setObjectName("txtDonationUsername")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtDonationUsername)
        self.label_9 = QtWidgets.QLabel(self.grpDonation)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtDonationAmount = QtWidgets.QLineEdit(self.grpDonation)
        self.txtDonationAmount.setReadOnly(True)
        self.txtDonationAmount.setObjectName("txtDonationAmount")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtDonationAmount)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.label_8 = QtWidgets.QLabel(self.grpDonation)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.txtDonationMessage = QtWidgets.QPlainTextEdit(self.grpDonation)
        self.txtDonationMessage.setReadOnly(True)
        self.txtDonationMessage.setObjectName("txtDonationMessage")
        self.verticalLayout_3.addWidget(self.txtDonationMessage)
        self.verticalLayout.addWidget(self.grpDonation)
        self.grpCheerSub = QtWidgets.QGroupBox(self.centralwidget)
        self.grpCheerSub.setObjectName("grpCheerSub")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grpCheerSub)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.grpCheerSub)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txtCheerSubUsername = QtWidgets.QLineEdit(self.grpCheerSub)
        self.txtCheerSubUsername.setReadOnly(True)
        self.txtCheerSubUsername.setObjectName("txtCheerSubUsername")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCheerSubUsername)
        self.label_11 = QtWidgets.QLabel(self.grpCheerSub)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtCheerAmount = QtWidgets.QLineEdit(self.grpCheerSub)
        self.txtCheerAmount.setReadOnly(True)
        self.txtCheerAmount.setObjectName("txtCheerAmount")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtCheerAmount)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.label_12 = QtWidgets.QLabel(self.grpCheerSub)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.txtCheerSubMessage = QtWidgets.QPlainTextEdit(self.grpCheerSub)
        self.txtCheerSubMessage.setReadOnly(True)
        self.txtCheerSubMessage.setObjectName("txtCheerSubMessage")
        self.verticalLayout_4.addWidget(self.txtCheerSubMessage)
        self.verticalLayout.addWidget(self.grpCheerSub)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Streamlabs Extractor"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.label.setText(_translate("MainWindow", "Streamlabs Alertbox URL:"))
        self.label_2.setText(_translate("MainWindow", "Twitch Client ID:"))
        self.label_3.setText(_translate("MainWindow", "Twitch Username:"))
        self.lblStatus.setText(_translate("MainWindow", "Disconnected"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.grpDonation.setTitle(_translate("MainWindow", "Media sharing and donations"))
        self.label_4.setText(_translate("MainWindow", "Last video title:"))
        self.label_5.setText(_translate("MainWindow", "Last video URL:"))
        self.label_6.setText(_translate("MainWindow", "Last stream timestamp:"))
        self.label_7.setText(_translate("MainWindow", "Username:"))
        self.label_9.setText(_translate("MainWindow", "Amount:"))
        self.label_8.setText(_translate("MainWindow", "Attached message:"))
        self.grpCheerSub.setTitle(_translate("MainWindow", "Cheers and subscribers"))
        self.label_10.setText(_translate("MainWindow", "Username:"))
        self.label_11.setText(_translate("MainWindow", "Cheer amount:"))
        self.label_12.setText(_translate("MainWindow", "Attached message:"))

